# Generated by Django 4.1.3 on 2023-07-18 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appUsuarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Camion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(default=None, max_length=255)),
                ("patente", models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Conductor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(default=None, max_length=255)),
                (
                    "email",
                    models.EmailField(
                        blank=True, default=None, max_length=254, unique=True
                    ),
                ),
                ("telefono", models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Registro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tracto", models.IntegerField(default=None)),
                ("cargado", models.BooleanField(default=None)),
                ("hora", models.DateTimeField(default=None)),
                ("fecha", models.DateField(default=None)),
                ("ppu", models.CharField(default=None, max_length=255)),
                ("contenedor", models.CharField(default=None, max_length=255)),
                ("sello", models.IntegerField(default=None, max_length=255)),
                (
                    "idCamion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appCentral.camion",
                    ),
                ),
                (
                    "idConductor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appCentral.conductor",
                    ),
                ),
                (
                    "idUsuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appUsuarios.usuario",
                    ),
                ),
            ],
        ),
    ]
