# Generated by Django 4.1.3 on 2023-07-18 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appCentral", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registro",
            name="sello",
            field=models.IntegerField(default=None),
        ),
    ]
