# Generated by Django 4.1.3 on 2023-07-18 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appCentral", "0002_alter_registro_sello"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registro",
            name="fecha",
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name="registro",
            name="hora",
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name="registro",
            name="sello",
            field=models.CharField(default=None, max_length=255),
        ),
    ]
