# Generated by Django 4.1.3 on 2023-07-27 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appCentral", "0003_alter_registro_fecha_alter_registro_hora_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="registro", name="idUsuario",),
    ]
