# Generated by Django 4.1.3 on 2023-07-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appUsuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="es_admin",
            field=models.CharField(max_length=255),
        ),
    ]
