# Generated by Django 4.1.3 on 2023-07-13 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appUsuarios", "0002_alter_usuario_es_admin"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usuario", old_name="constraseña", new_name="contraseña",
        ),
    ]
