# Generated by Django 4.1.3 on 2023-07-14 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RemoveField(model_name="usuario", name="contraseña",),
    ]
