# Generated by Django 4.1.3 on 2023-07-14 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appUsuarios", "0003_rename_constraseña_usuario_contraseña"),
    ]

    operations = [
        migrations.RemoveField(model_name="usuario", name="contraseña",),
    ]
